//import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import ChakraProviders from "./ChakraProviders";
import SidebarWithHeader from "./components/SidebarWithHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProviders>
          <SidebarWithHeader>{children}</SidebarWithHeader>
        </ChakraProviders>
      </body>
    </html>
  );
}
